"""habitudes progressives: duree et unite personnalisees

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-16 08:07:49.225878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progressive_weeks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('progressive_unit', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('progressive_unit')
        batch_op.drop_column('progressive_weeks')

    # ### end Alembic commands ###
