"""import montre (health connect)

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-16 14:18:40.517487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date_key', sa.String(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date_key', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('other_sport_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate_avg', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate_max', sa.Integer(), nullable=True))

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate_avg', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate_max', sa.Integer(), nullable=True))

    with op.batch_alter_table('strength_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate_avg', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate_max', sa.Integer(), nullable=True))

    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.drop_column('external_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('strength_sessions', schema=None) as batch_op:
        batch_op.drop_column('heart_rate_max')
        batch_op.drop_column('heart_rate_avg')
        batch_op.drop_column('external_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('heart_rate_max')
        batch_op.drop_column('heart_rate_avg')
        batch_op.drop_column('external_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('other_sport_logs', schema=None) as batch_op:
        batch_op.drop_column('heart_rate_max')
        batch_op.drop_column('heart_rate_avg')
        batch_op.drop_column('external_id')
        batch_op.drop_column('source')

    op.drop_table('sleep_logs')
    op.drop_table('daily_steps')
    # ### end Alembic commands ###
